### ISSUE TITLE
GetCells does not work when key contains colons

### ISSUE THREAD

**Issue by pawelpabich** [hdinsight/hbase-sdk-for-net#26]
Hi,

I have a key that follows this pattern: "Guid_DateTimeOffset.ToString("0")". Sample key: "b7c5510bed2c400b9ecf51df24a735eb_2015-06-26T10:35:00.5325853+10:00". When I try to use this key to retrieve the date I get 404. When I use HBase shell I can find the data without any problems.

**Comment by pawelpabich** [comment]
Same problem with "+" sign

**Comment by duoxu** [comment]
@pawelpabich I am working on this, basically adding a new endpoint to our Gateway, which looks like "https://<cluster_dnsname>.azurehdinsight.net/hbaserestsecure/<base64 encoded REST API>", in our Gateway the API will be decoded and forwarded to REST servers inside the cluster. Since the API is base64 encoded, the IIS module on Gateway will not find ":", "+" or other dangerous characters in your url request and send you 404.

**Comment by pawelpabich** [comment]
@duoxu you also encode url parameters using something like HttpServerUtility.UrlEncode on the client side. HBase rest server should support encoding, same with IIS. This might be much less work.

**Comment by duoxu** [comment]
@pawelpabich Our gateway owner does not like my solution and suggests if we can turn off IIS validation for hbaserest endpoint in IIS. Anyway, this would not be a trivial fix.

**Comment by pawelpabich** [comment]
@duoxu out of curiosity, have you tried encoding that I mentioned above? This is how you deal with this problem in regular Web Apps

**Comment by duoxu** [comment]
@pawelpabich One customer reported changing ":" to "%3A" does not work.

**Comment by pawelpabich** [comment]
interesting, was that IIS or HBase that thew error ?

**Comment by duoxu** [comment]
@pawelpabich  IIS. it is not easy to cheat IIS.

**Comment by pawelpabich** [comment]
Do you know if other web severs suffer from this problem?

**Comment by duoxu** [comment]
no.

**Comment by duoxu** [comment]
VNET mode will work.
